version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=fksKBybsHJs#34
      - POSTGRES_USER=fotistsiskakis
      - POSTGRES_DB=bet_strategist
  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    depends_on:
      - postgres
    command: [ "java", "-jar", "betstrategist.jar" ]