spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bet_strategist
    username: fotistsiskakis
    password: fksKBybsHJs#34
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true